import { GoogleGenAI, Modality } from "@google/genai";
import { DesignStyle } from "../types";

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove the data:image/xyz;base64, prefix for transmission
      const base64Data = result.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = (error) => reject(error);
  });
};

export const generateRoomDesign = async (
  imageFile: File, 
  style: DesignStyle, 
  customInstructions: string,
  isRoomEmpty: boolean = false,
  apiKey: string
): Promise<string> => {
  try {
    if (!apiKey) {
      throw new Error("API Key is missing");
    }

    const ai = new GoogleGenAI({ apiKey });
    const base64Image = await fileToBase64(imageFile);

    let prompt;

    if (isRoomEmpty) {
      prompt = `Act as a professional interior designer.
      Input: An image of an empty or sparse room.
      Goal: Fully furnish and decorate this room in the ${style.name} style.
      
      Style Description: ${style.promptModifier}.
      
      Instructions:
      1. Maintain the exact architectural structure (walls, floor, ceiling, windows, doors).
      2. Place appropriate furniture, rugs, lighting, and decor into the room.
      3. Ensure the furniture arrangement is functional and realistic.
      4. The lighting should match the natural light sources in the image.
      5. Populate the room significantly to show a complete design.
      ${customInstructions ? `Additional User Request: ${customInstructions}` : ''}
      
      Output: A single, high-quality, photorealistic image of the completed room design.`;
    } else {
      prompt = `Act as a professional interior designer.
      Input: An image of a furnished room.
      Goal: Redesign this room in the ${style.name} style.
      
      Style Description: ${style.promptModifier}.
      
      Instructions:
      1. Maintain the exact architectural structure (walls, floor, ceiling, windows, doors).
      2. Replace the existing furniture, decor, and colors with new items matching the target style.
      3. Keep the camera angle and perspective exactly the same.
      ${customInstructions ? `Additional User Request: ${customInstructions}` : ''}
      
      Output: A single, high-quality, photorealistic image of the redesign.`;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image, 
              mimeType: 'image/jpeg',
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model");

  } catch (error) {
    console.error("Error generating design:", error);
    throw error;
  }
};